dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
  
notifications:
  email: false

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - npm config set spin false
  - npm config set progress false
  
install:
  - npm install --no-optional

before_script:
  - npm start &
  - sleep 10

script:
  - npm run lint
  - npm run slint
  - npm run e2e
  # TODO: needs solution for router testing in template
  # - npm run test
